@startuml "Поликлиника - последовательность"
participant Пациент
participant Врач
participant Медкнижка

Пациент -> Врач: 1. Приходить на приём
Врач -> Медкнижка: 2. Постановка на учёт
Врач -> Медкнижка: 3. Запись приёма
Врач -> Пациент: 4. Осмотр больного
Врач -> Пациент: 5. Консультирование больного
Врач -> Медкнижка: 6. Ведение медкнижки
Врач -> Пациент: 7.Лечение
Врач -> Медкнижка: 8. Снятие с учёта
@enduml