@startuml "Поликлиника - диаграмма системы"
left to right direction
skinparam packageStyle rect
actor регистратура
actor врач
rectangle Поликлиника {
(Ведение медицинской карты) -- регистратура
врач -- (Ведение истории болезни)
(Ведение медицинской карты) <- (Ведение истории болезни)
врач -- (Ведение медицинской карты)
врач -- (Запись на приём к врачу)
(Запись на приём к врачу) -- регистратура
регистратура -- (Оповещение о приёме к врачу)
}
@enduml