@startuml "Диаграмма развёртывания"
top to bottom direction

node Пациент{
    artifact "Жалобы"
}

node Врач{
    artifact "Специализация"
}

Врач 0--0 Пациент: Консультация
node Регистратура{
node "Архив медкнижек" {
    artifact "Медкнижка"
}
node Записи{
artifact "Приём"
}
}

Регистратура --0 Пациент: Запись на приём
Врач 0-- Регистратура: Доступ к медкнижкам и записям
@enduml